### ISSUE TITLE
párbeszédes megjelenítés kellene

### ISSUE THREAD

**Issue by agneskovacs-h** [devpiciakk/vvchatbot#1]
1. Látszódjon a felhasználó által írt vagy kiválasztott kérdés  - történeti sorrendben
2. Formázás is kellene: balra és jobbra igazítással a két szereplő által mondott / kérdezett dolgok. Nem teljes képernyő szélességben, hanem valami értelmes, / jól kinéző szélességben

**Comment by devpiciakk** [comment]
Dear agneskovacs-h,

The email sent to hello@robin1.tk with subject
"[devpiciakk/vvchatbot] párbeszédes"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to hello@robin1.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by devpiciakk** [comment]
Dear agneskovacs-h,

The email sent to hello@robin1.tk with subject
"Re: [devpiciakk/vvchatbot] párbeszédes"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to hello@robin1.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
