### ISSUE TITLE
A gombok 2 csoportjának megjelenítésbeli elkülönítése

### ISSUE THREAD

**Issue by agneskovacs-h** [devpiciakk/vvchatbot#2]
A gombok 2 csoportba tartoznak: 
(1) előre megírt kérdés 
(2) eldöntendő kérdésre adott válasz segédlet
A felhasználónak a megjelenítéssel segíteni kell ezt azt infót átadni.
Minimum, hogy külön sorba kerüljenek a gombok.
Optimális az lenne, hogy az Igen / Nem gombok csak akkor kerüljenek megjelenítésre, ha a felhasználónak kell válaszolni egy eldöntendő kérdésre. Pl. "Már regisztrált magának felhasználót?"

**Comment by devpiciakk** [comment]
Dear agneskovacs-h,

The email sent to hello@robin1.tk with subject
"[devpiciakk/vvchatbot] A gombok 2 csoportjának me"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to hello@robin1.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by devpiciakk** [comment]
Dear agneskovacs-h,

The email sent to hello@robin1.tk with subject
"Re: [devpiciakk/vvchatbot] A gombok 2 csoportjának"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to hello@robin1.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
